; HEADER_BLOCK_START
; generated by OrcaSlicer 2.1.1 on 2025-07-15 at 17:15:16
; total layer number: 1
; filament_density: 1.3
; filament_diameter: 1.75
; max_z_height: 0.28
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 48x48 416
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA/klEQVR4Ae2YvQ3CUAyEXdBQIH6CQH
; RISGxAgUQRGmigSpWKNNCxQzbJKKyGPECeXUTR3ZO/9jWx7myfIxIEQRAMzaRY7YUZLWD3ff+EnaJ6
; dtPjoRR0UpbRApaPeyvIaAHruupS72op+N6wLKNKwKthWUZV2H5e2A3usQxFg1uWoWnwlGX0fdPU+G
; pYllncrnk0eGocQ+CxDEWDW5ahUcPaCRRqWB9JMW71I7PIU1oEfZ6al5c2izylatDnKR23s/Op6Xun
; yVOpGzvy1JjEwYSEtROyyVPWcoTAsoy1HCHwHkzQecqzE7TI1HKEwHMwCToUU8gDzV/yIAiCYHT+kh
; hy5gnOKVsAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 2172
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAGJElEQVR4Ae3dzWplVRAF4APtRMglmE
; aJtk2iDY4VjBAhYnAgSiONICJOkpFBREQFfzAQEYwTBXHkKI/Sj9KPcuUMAnY4md+19vfBfYQcqiq1
; ak8TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD
; CkZ+7u7O/9/suT5x6+fzEBbKrV4cHJg3//Wl//Xvruy8cTwCbaPj66un/xw/r/H6252nr2tQfvTgCb
; 6MWvv1jv//nbUx+uF04+u5oANtHzn3/yRLUFxNh68/WLe99/9dRHa/4ZyAMba6lFnAfy838UJ4BNs/
; PRB49f/vlbLSKQ47ZqawLYRHO1ZSAPxLgeyL/6zx8G8kCGpRZxrrYM5IGNNLeI1h+AKAbyQBQDeSDK
; PJCfqy0DeSCGPCIQZT5ZYyAPA5r/yFOrEwN5GMS80zR/rNKrEwN5GMDq7bcumpYzHQiEckvXEpKrLQ
; N5GEDTLMiBQBhA2yxIHhHKtS1ntrW8wIK2WZD1ByjXdi3B+gMMoG0gL48I5dqqk92z07VqC8o1LWc6
; EAgDMJAHorQtZxrIwwDaXm+WR4Ryty1nrg4PTqZA8ogwAHlEIMoIecTklhe4oe315qWWd/4Ip7a8wI
; J5OXPv8rz6QKD1BygijwjEaRzIyyNCscaBfFPLCyxoOxBo/QHKySMCUeQRgTgOBAJR2qoTeUQYQNO1
; BHlEGMAoecQJ6GAgD8Rpe73ZgUAo1/Z6s2oLBuBAIBBlhIG8PCIUaVvObGt5gQXyiECU7eOjK+sPQB
; R5RCCKPCIQp2k504FAGICBPBBFHhGII48IRGlbzjSQhwHIIwJR5BGBKKPkEVeHBycT0GH37HRt/QGI
; 0bacaf0BBiCPCERpq07mlnfv8ly1Bc3kEYEo8ohAFHlEIM5t1UlyHvHmQF4eEYosLWc6EAhsNHlEIM
; oIecTklhe44bo6acojahGh3AgHAq0/QBF5RCBO40BeHhGKORAIRBnlQKBqC4rIIwJRto+PrgzkgSgO
; BAJR2qoTeUQYQNOBwLaWF1gwSh5xAjo4EAjEGSGP6EAgFGlbzjSQhwE4EAhEkUcEosgjAnHkEYEoDg
; QCceQRgSht1cnu2elatQXlmpYz21peYIGBPBBFHhGI0/Z6szwilLttOXN1eHAyBZJHhAHIIwJRRjkQ
; KI8IJdpeb15qeeePcGrLCyyYq5O9y/PqA4HWH6CIPCIQp3EgL48IxRoH8k0tL3DDndXWftuBQOsPUE
; 4eEYgijwjEcSAQiNJWncgjwgCariXII8IARskjTkAHA3kgTtvrzQ4EQrm215tVWzAABwKBKCMM5OUR
; oUjbcmZbywsskEcEomwfH11ZfwCiyCMCUeQRgThNy5kOBMIADOSBKPKIQBx5RCBK23KmgTwMQB4RiD
; LKgUB5RCgxSh5xdXhwMgEdds9OF19vtv4AbKS25UzrDzCAxoG8PCIUa6tObmt5DeShiDwiEEUeEYgi
; jwjEaVvOdCAQyi0tZzoQCGw0eUQgyih5xAno0LacaSAPA3AgEIjSdiBQtQUDMJAHoowwkJdHhCKjHA
; hUbUEReUQgyvbx0ZU8IhClbSAvjwjl2qoTeUQYQNNyZlvLCywwkAeiOBAIxJFHBKK0LWcayMMA5BGB
; KPKIQBR5RCDO/Hqz9QcgRtvrzdYfYADyiECUtuqkreUFFjQtZ7a1vMACeUQgijwiEOe26kQeEdhIS8
; uZc3WyOjw4mQLJI8IA5BGBKCPkEZNbXuCG6+qkOY+oRYQyc3Wyd3lefSDQ+gMUkUcE4jQO5OURoZgD
; gUCUxgOB1h+gnDwiEKU9j3j/1x/XWwdvXExAj8YDgfd++ma9/d47Kixo1DaQv7Pa2p+Abq4lAFEsZw
; JRXEsA4ljOBKJ4vRmIYzkTiGIgD0TxejMQx2MRQBTXEoA4BvJAFAN5II48IhDFQB6IIo8IxLnZIr7y
; 9+V659GHWkRgM13nEeeP1d1PHz2ZADbdzscPfawAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYGD/AW4GpuuuokZnAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.45mm

; EXECUTABLE_BLOCK_START
M73 P0 R1
M201 X500 Y500 Z100 E5000
M203 X500 Y500 Z10 E60
M204 P500 R1000 T500
M205 X8.00 Y8.00 Z0.40 E5.00 ; sets the jerk limits, mm/sec
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
; ======== Change Temperatura ========
M104 S255 ; set final nozzle temp
; ====================================
M140 S75 ; set final bed temp
G4 S20 ; allow partial nozzle warmup
G28 ; home all axis and restore leveling
G1 Z50 F240
G1 X2.0 Y10 F3000
; ======== Change temperature ========
M109 S255 ; wait for nozzle temp to stabilize
; ====================================
M190 S75 ; wait for bed temp to stabilize
M73 P20 R0
G1 Z0.28 F240

G92 E0
M73 P21 R0
G1 X2.0 Y140 E10 F1500  prime the nozzle
M73 P42 R0
G1 X2.3 Y140 F5000
G92 E0
M73 P51 R0
G1 X2.3 Y10 E10 F1200  prime the nozzle
G92 E0

M118 START_MONITOR ; Starts monitoring

; ======== Change Z-Offset ========
;M206 Z0.1
;M206 Z-0.1
; =================================

G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 S0
;LAYER_CHANGE
;Z:0.28
;HEIGHT:0.28
;BEFORE_LAYER_CHANGE
;0.28
G92 E0

G1 E-.8 F1500
M118 LAYER_NUMBER_1
;_SET_FAN_SPEED_CHANGING_LAYER
M73 P62 R0
G1 Z.4 F2400
G1 X188.995 Y30 F7200
G1 Z.4
M73 P70 R0
G1 Z.28
G1 E.8 F1800
;TYPE:Skirt
;WIDTH:0.45
G1 F3000
G1 X189.392 Y27.896 E.09718
G1 X190.527 Y26.081 E.09718
G1 X192.245 Y24.803 E.09718
G1 X194.775 Y24.22 E.11785
G1 X200.225 Y24.22 E.24737
G1 X202.329 Y24.617 E.09718
M73 P71 R0
G1 X204.144 Y25.752 E.09718
G1 X205.422 Y27.47 E.09718
G1 X206.005 Y30 E.11785
G1 X206.005 Y80 E2.26949
G1 X205.608 Y82.104 E.09718
M73 P73 R0
G1 X204.473 Y83.919 E.09718
G1 X202.755 Y85.197 E.09718
G1 X200.225 Y85.78 E.11785
G1 X194.775 Y85.78 E.24737
G1 X192.671 Y85.383 E.09718
G1 X190.856 Y84.248 E.09718
G1 X189.578 Y82.53 E.09718
G1 X188.995 Y80 E.11785
M73 P74 R0
G1 X188.995 Y30.04 E2.26767
G1 X189.385 Y30.04 F2400
M73 P75 R0
G1 F3000
G1 X189.385 Y30 E.00182
G1 X189.781 Y27.971 E.09381
G1 X190.912 Y26.241 E.09381
M73 P76 R0
G1 X192.611 Y25.064 E.09381
G1 X194.775 Y24.61 E.10038
G1 X200.225 Y24.61 E.24737
G1 X202.254 Y25.006 E.09381
G1 X203.984 Y26.137 E.09381
G1 X205.161 Y27.836 E.09381
G1 X205.615 Y30 E.10038
G1 X205.615 Y80 E2.26949
G1 X205.219 Y82.029 E.09381
M73 P78 R0
G1 X204.088 Y83.759 E.09381
G1 X202.389 Y84.936 E.09381
G1 X200.225 Y85.39 E.10038
G1 X194.775 Y85.39 E.24737
M73 P79 R0
G1 X192.746 Y84.994 E.09381
G1 X191.016 Y83.863 E.09381
G1 X189.839 Y82.164 E.09381
G1 X189.385 Y80 E.10038
G1 X189.385 Y30.08 E2.26586
; printing object Assembly id:0 copy 0
G1 E-.3 F1500
;WIPE_START
M73 P81 R0
G1 F3000
G1 X189.385 Y30 E-.04
G1 X189.561 Y29.097 E-.46
;WIPE_END
G1 Z.68 F2400
G1 X200 Y30.225 Z.68 F7200
G1 Z.28 F2400
M73 P84 R0
G1 E.8 F1800
;TYPE:Outer wall
;WIDTH:0.450001
; ======== CHANGE SPEED ========
G1 F2400
; ==============================
G1 X200 Y79.775 E2.24907
G1 E-.175 F1500
;WIPE_START
M73 P86 R0
G1 F2400
G1 X200 Y80.775 E-.625
;WIPE_END
G1 Z.68
G1 X195 Y79.775 Z.68
G1 Z.28
M73 P88 R0
G1 E.8 F1800
M73 P89 R0
; ======== CHANGE SPEED ========
G1 F2400
; ==============================
G1 X195 Y30.225 E2.24907
; stop printing object Assembly id:0 copy 0
G1 E-.175 F1500
;WIPE_START
M73 P91 R0
G1 F2400
G1 X195 Y31.225 E-.625
;WIPE_END
M106 S0
;TYPE:Custom
; filament end gcode 
; Ensure print head is safely clear of the printed object
G91 ; Set relative coordinates
G1 Z2.28 F1200 ; Lift print head safely above the finished print. Using max_layer_z to clear the highest point + a small offset (5mm).
G90 ; Set absolute coordinates

; Clear the space for the photo
G1 Y10 F7200
M73 P92 R0
G1 X10 F7200
M73 P93 R0
G1 Y110 F7200
M73 P95 R0
G1 Z15 F480

M118 STOP_MONITOR ; Stops monitoring

M107 ; turn off fan
M84 X Y E ; disable motors

M118 TAKE_PHOTO; Printing finished and space is clear to take the photo}

M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 16.93
; filament used [cm3] = 0.04
; filament used [g] = 0.05
; filament cost = 0.00; total filament used [g] = 0.05
; total filament cost = 0.00
; total layers count = 1
; estimated printing time (normal mode) = 59s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; additional_cooling_fan_speed = 70
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0.24
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonicline
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 25
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.15
; brim_type = no_brim
; brim_width = 2.4
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = M600
; close_fan_the_first_x_layers = 2
; complete_print_exhaust_fan_speed = 80
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 60
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 0
; default_filament_colour = #000000
; default_filament_profile = "Creality Generic PLA"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @Creality Ender3S1Pro
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 1
; different_settings_to_system = bottom_shell_layers;bottom_shell_thickness;bottom_surface_pattern;brim_object_gap;brim_type;brim_width;elefant_foot_compensation;gap_infill_speed;initial_layer_infill_speed;initial_layer_line_width;initial_layer_print_height;initial_layer_speed;initial_layer_travel_speed;inner_wall_line_width;internal_solid_infill_pattern;internal_solid_infill_speed;outer_wall_line_width;skirt_distance;skirt_height;small_perimeter_speed;sparse_infill_density;sparse_infill_line_width;sparse_infill_pattern;sparse_infill_speed;support_line_width;top_shell_layers;top_shell_thickness;top_surface_line_width;top_surface_speed;travel_speed;close_fan_the_first_x_layers;default_filament_colour;fan_max_speed;fan_min_speed;filament_density;filament_flow_ratio;filament_retract_restart_extra;filament_retraction_length;filament_retraction_minimum_travel;filament_retraction_speed;filament_type;filament_vendor;filament_z_hop;hot_plate_temp;hot_plate_temp_initial_layer;nozzle_temperature;nozzle_temperature_initial_layer;nozzle_temperature_range_high;nozzle_temperature_range_low;layer_change_gcode;machine_end_gcode;machine_start_gcode;nozzle_type
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 60
; elefant_foot_compensation = 0
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 60
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 0
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 34
; extruder_clearance_height_to_rod = 34
; extruder_clearance_radius = 47
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 20
; fan_min_speed = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #26A69A
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.3
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 1
; filament_ids = GFL99
; filament_is_support = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 12
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_restart_extra = 0
; filament_retraction_length = 0.8
; filament_retraction_minimum_travel = 1
; filament_retraction_speed = 25
; filament_settings_id = "Fiberon PETG-rCF08"
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_toolchange_delay = 0
; filament_type = PETG-CF
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Fiberon
; filament_z_hop = 0.4
; filename_format = {input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_target = nowhere
; gap_infill_speed = 40
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 75
; hot_plate_temp_initial_layer = 75
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @Creality Ender3S1Pro";"Creality Generic PLA";"Creality Ender-3 S1 Pro 0.4 nozzle"
; initial_layer_acceleration = 0
; initial_layer_infill_speed = 40
; initial_layer_jerk = 9
; initial_layer_line_width = 0
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.28
; initial_layer_speed = 40
; initial_layer_travel_speed = 40
; inner_wall_acceleration = 0
; inner_wall_jerk = 9
; inner_wall_line_width = 0
; inner_wall_speed = 40
; interface_shells = 0
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0
; internal_solid_infill_pattern = zig-zag
; internal_solid_infill_speed = 40
; ironing_angle = -1
; ironing_flow = 15%
; ironing_pattern = zig-zag
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = M118 LAYER_NUMBER_{layer_num+1}
; layer_height = 0.2
; line_width = 0.45
; long_retractions_when_cut = 0
; machine_end_gcode = \n; Ensure print head is safely clear of the printed object\nG91 ; Set relative coordinates\nG1 Z{z_offset+min(max_layer_z+5, printable_height)} F600 ; Lift print head safely above the finished print. Using max_layer_z to clear the highest point + a small offset (5mm).\nG90 ; Set absolute coordinates\n\n; Clear the space for the photo\nG1 Y10 F{travel_speed*60}\nG1 X10 F{travel_speed*60}\nG1 Y120 F{travel_speed*60}\nG1 Z15 F{travel_speed*4}\n\nM118 STOP_MONITOR ; Stops monitoring\n\nM107 ; turn off fan\nM84 X Y E ; disable motors\n\nM118 TAKE_PHOTO; Printing finished and space is clear to take the photo}\n\n
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 500,500
; machine_max_acceleration_retracting = 1000,1000
; machine_max_acceleration_travel = 1000,1000
; machine_max_acceleration_x = 500,500
; machine_max_acceleration_y = 500,500
; machine_max_acceleration_z = 100,100
; machine_max_jerk_e = 5,5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_max_speed_e = 60,60
; machine_max_speed_x = 500,500
; machine_max_speed_y = 500,500
; machine_max_speed_z = 10,10
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M25
; machine_start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\n; ======== Change Temperatura ========\nM104 S[nozzle_temperature_initial_layer] ; set final nozzle temp\n; ==================================\nM140 S[bed_temperature_initial_layer_single] ; set final bed temp\nG4 S20 ; allow partial nozzle warmup\nG28 ; home all axis and restore leveling\nG1 Z50 F240\nG1 X2.0 Y10 F3000\n; ======== Change temperature ========\nM109 S[nozzle_temperature_initial_layer] ; wait for nozzle temp to stabilize\n; ==================================\nM190 S[bed_temperature_initial_layer_single] ; wait for bed temp to stabilize\nG1 Z0.28 F240\nM118 START_MONITOR ; Starts monitoring\nG92 E0\nG1 X2.0 Y140 E10 F1500 ; prime the nozzle\nG1 X2.3 Y140 F5000\nG92 E0\nG1 X2.3 Y10 E10 F1200 ; prime the nozzle\nG92 E0\n\n; ======== Change Z-Offset ========\n;M206 Z0.1\n;M206 Z-0.1
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.36
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 10
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 4
; nozzle_hrc = 0
; nozzle_temperature = 255
; nozzle_temperature_initial_layer = 255
; nozzle_temperature_range_high = 270
; nozzle_temperature_range_low = 220
; nozzle_type = brass
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 500
; outer_wall_jerk = 9
; outer_wall_line_width = 0
; outer_wall_speed = 40
; overhang_1_4_speed = 0
; overhang_2_4_speed = 20
; overhang_3_4_speed = 15
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "Creality Ender-3 S1 Pro 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Ender3S1Pro - PETG-rCF08
; printable_area = 0x0,220x0,220x220,0x220
; printable_height = 270
; printer_model = Creality Ender-3 S1 Pro
; printer_notes = 
; printer_settings_id = Creality Ender-3 S1 Pro 0.4 nozzle - Test2
; printer_structure = i3
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 0%
; retract_length_toolchange = 1
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; rotate_solid_infill_direction = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 1
; skirt_distance = 5
; skirt_height = 1
; skirt_loops = 2
; skirt_speed = 50
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 8
; slow_down_layers = 0
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 0
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 40
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 100%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0
; sparse_infill_pattern = zig-zag
; sparse_infill_speed = 40
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 0
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 0.2
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 0
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = -1
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.2
; support_interface_speed = 80
; support_interface_top_layers = 3
; support_line_width = 0
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 40
; support_style = grid
; support_threshold_angle = 30
; support_top_z_distance = 0.15
; support_type = normal(auto)
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 48x48/PNG,300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 3
; top_shell_thickness = 0.24
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 0
; top_surface_jerk = 9
; top_surface_line_width = 0
; top_surface_pattern = monotonicline
; top_surface_speed = 40
; travel_acceleration = 0
; travel_jerk = 12
; travel_speed = 120
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 40
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 2
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 0.000
; wipe_tower_y = 250.000
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 75
; bed_shape = 0x0,220x0,220x220,0x220
; first_layer_temperature = 255
; first_layer_height = 0.280
; CONFIG_BLOCK_END


